// <auto-generated />
using System;
using BroadlinkWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BroadlinkWeb.Migrations
{
    [DbContext(typeof(Dbc))]
    partial class DbcModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BroadlinkWeb.Models.Entities.BrDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("DeviceTypeDetailNumber")
                        .HasColumnType("int(6)");

                    b.Property<string>("IpAddressString")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MacAddressString")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Port")
                        .HasColumnType("int(5)");

                    b.HasKey("Id");

                    b.ToTable("brdevices");

                    b.HasAnnotation("MySQL:Charset", "utf8");

                    b.HasAnnotation("MySQL:Collation", "utf8_general_ci ");
                });

            modelBuilder.Entity("BroadlinkWeb.Models.Entities.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ControlSetId")
                        .HasColumnType("int(11)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("IsAssignToggleOff")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("IsAssignToggleOn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PositionLeft")
                        .HasColumnType("int(11)");

                    b.Property<int>("PositionTop")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("ControlSetId");

                    b.ToTable("controls");

                    b.HasAnnotation("MySQL:Charset", "utf8");

                    b.HasAnnotation("MySQL:Collation", "utf8_general_ci ");

                    b.HasData(
                        new { Id = 1, Code = "", Color = "#F92068", ControlSetId = 1, IconUrl = "images/icons/power.png", IsAssignToggleOff = (byte)1, IsAssignToggleOn = (byte)1, Name = "Power", PositionLeft = 185, PositionTop = 5 },
                        new { Id = 2, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_0.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.0", PositionLeft = 95, PositionTop = 545 },
                        new { Id = 3, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_9.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.9", PositionLeft = 185, PositionTop = 455 },
                        new { Id = 4, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_8.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.8", PositionLeft = 95, PositionTop = 455 },
                        new { Id = 5, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_7.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.7", PositionLeft = 5, PositionTop = 455 },
                        new { Id = 6, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_6.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.6", PositionLeft = 185, PositionTop = 365 },
                        new { Id = 7, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_5.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.5", PositionLeft = 95, PositionTop = 365 },
                        new { Id = 8, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_4.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.4", PositionLeft = 5, PositionTop = 365 },
                        new { Id = 9, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_3.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.3", PositionLeft = 185, PositionTop = 275 },
                        new { Id = 10, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_2.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.2", PositionLeft = 95, PositionTop = 275 },
                        new { Id = 11, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_1.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.1", PositionLeft = 5, PositionTop = 275 },
                        new { Id = 12, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/circle_minus.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Vol.Down", PositionLeft = 5, PositionTop = 185 },
                        new { Id = 13, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/circle_plus.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Vol.Up", PositionLeft = 5, PositionTop = 95 },
                        new { Id = 14, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/arrow2_down.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.Down", PositionLeft = 185, PositionTop = 185 },
                        new { Id = 15, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/arrow2_up.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.Up", PositionLeft = 185, PositionTop = 95 },
                        new { Id = 16, Code = "", Color = "#84bde8", ControlSetId = 1, IconUrl = "images/icons/settings2.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Input Select", PositionLeft = 5, PositionTop = 5 },
                        new { Id = 17, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_aster.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.Aster", PositionLeft = 5, PositionTop = 545 },
                        new { Id = 18, Code = "", Color = "#9d9e9e", ControlSetId = 1, IconUrl = "images/icons/num_sharp.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.Sharp", PositionLeft = 185, PositionTop = 545 },
                        new { Id = 19, Code = "", Color = "#F92068", ControlSetId = 2, IconUrl = "images/icons/power.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)1, Name = "Power On", PositionLeft = 5, PositionTop = 5 },
                        new { Id = 20, Code = "", Color = "#6545C6", ControlSetId = 2, IconUrl = "images/icons/moon.png", IsAssignToggleOff = (byte)1, IsAssignToggleOn = (byte)0, Name = "Power Off", PositionLeft = 185, PositionTop = 5 },
                        new { Id = 21, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/circle_plus.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Vol.Up", PositionLeft = 5, PositionTop = 95 },
                        new { Id = 22, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/circle_minus.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Vol.Down", PositionLeft = 5, PositionTop = 185 },
                        new { Id = 23, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/arrow2_up.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.Up", PositionLeft = 185, PositionTop = 95 },
                        new { Id = 24, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/arrow2_down.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Ch.Down", PositionLeft = 185, PositionTop = 185 },
                        new { Id = 25, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/circle_play.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Play", PositionLeft = 95, PositionTop = 275 },
                        new { Id = 26, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/darrow_right.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Next", PositionLeft = 185, PositionTop = 365 },
                        new { Id = 27, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/darrow_left.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Prev", PositionLeft = 5, PositionTop = 365 },
                        new { Id = 28, Code = "", Color = "#9d9e9e", ControlSetId = 2, IconUrl = "images/icons/circle_pause.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Pause", PositionLeft = 95, PositionTop = 365 },
                        new { Id = 29, Code = "", Color = "#F92068", ControlSetId = 3, IconUrl = "images/icons/power.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)1, Name = "Power On", PositionLeft = 5, PositionTop = 5 },
                        new { Id = 30, Code = "", Color = "#6545C6", ControlSetId = 3, IconUrl = "images/icons/moon.png", IsAssignToggleOff = (byte)1, IsAssignToggleOn = (byte)0, Name = "Power Off", PositionLeft = 185, PositionTop = 5 },
                        new { Id = 31, Code = "", Color = "#9d9e9e", ControlSetId = 3, IconUrl = "images/icons/arrow2_up.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Up", PositionLeft = 95, PositionTop = 95 },
                        new { Id = 32, Code = "", Color = "#9d9e9e", ControlSetId = 3, IconUrl = "images/icons/arrow2_down.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Down", PositionLeft = 95, PositionTop = 185 },
                        new { Id = 33, Code = "", Color = "#F92068", ControlSetId = 4, IconUrl = "images/icons/power.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)1, Name = "Power On", PositionLeft = 5, PositionTop = 5 },
                        new { Id = 34, Code = "", Color = "#6545C6", ControlSetId = 4, IconUrl = "images/icons/moon.png", IsAssignToggleOff = (byte)1, IsAssignToggleOn = (byte)0, Name = "Power Off", PositionLeft = 185, PositionTop = 5 },
                        new { Id = 35, Code = "", Color = "#9d9e9e", ControlSetId = 4, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Temp.", PositionLeft = 95, PositionTop = 95 },
                        new { Id = 36, Code = "", Color = "#9d9e9e", ControlSetId = 4, IconUrl = "images/icons/settings2.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Select", PositionLeft = 5, PositionTop = 185 },
                        new { Id = 37, Code = "", Color = "#9d9e9e", ControlSetId = 4, IconUrl = "images/icons/arrow2_up.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Up", PositionLeft = 185, PositionTop = 95 },
                        new { Id = 38, Code = "", Color = "#9d9e9e", ControlSetId = 4, IconUrl = "images/icons/arrow2_down.png", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Down", PositionLeft = 185, PositionTop = 185 },
                        new { Id = 39, Code = "", Color = "#F92068", ControlSetId = 5, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Temp.", PositionLeft = 185, PositionTop = 5 },
                        new { Id = 40, Code = "", Color = "#84bde8", ControlSetId = 5, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Humidity", PositionLeft = 5, PositionTop = 5 },
                        new { Id = 41, Code = "", Color = "#81c03b", ControlSetId = 5, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "VOC", PositionLeft = 95, PositionTop = 95 },
                        new { Id = 42, Code = "", Color = "#fcc91f", ControlSetId = 5, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Light", PositionLeft = 5, PositionTop = 185 },
                        new { Id = 43, Code = "", Color = "#B5743B", ControlSetId = 5, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Noise", PositionLeft = 185, PositionTop = 185 },
                        new { Id = 44, Code = "", Color = "#F92068", ControlSetId = 6, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Power", PositionLeft = 95, PositionTop = 5 },
                        new { Id = 45, Code = "", Color = "#9d9e9e", ControlSetId = 6, IconUrl = "", IsAssignToggleOff = (byte)0, IsAssignToggleOn = (byte)0, Name = "Night light", PositionLeft = 95, PositionTop = 95 }
                    );
                });

            modelBuilder.Entity("BroadlinkWeb.Models.Entities.ControlSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int?>("BrDeviceId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("IsTemplate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrDeviceId");

                    b.ToTable("controlsets");

                    b.HasAnnotation("MySQL:Charset", "utf8");

                    b.HasAnnotation("MySQL:Collation", "utf8_general_ci ");

                    b.HasData(
                        new { Id = 1, Color = "#fcc91f", IsTemplate = (byte)1, Name = "TV" },
                        new { Id = 2, Color = "#F92068", IsTemplate = (byte)1, Name = "AV" },
                        new { Id = 3, Color = "#ccdc4b", IsTemplate = (byte)1, Name = "Light" },
                        new { Id = 4, Color = "#6545C6", IsTemplate = (byte)1, Name = "Air Complessor" },
                        new { Id = 5, Color = "#84bde8", IsTemplate = (byte)1, Name = "A1 Sensor" },
                        new { Id = 6, Color = "#84bde8", IsTemplate = (byte)1, Name = "Sp2 Switch" }
                    );
                });

            modelBuilder.Entity("BroadlinkWeb.Models.Entities.Control", b =>
                {
                    b.HasOne("BroadlinkWeb.Models.Entities.ControlSet", "ControlSet")
                        .WithMany("Controls")
                        .HasForeignKey("ControlSetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BroadlinkWeb.Models.Entities.ControlSet", b =>
                {
                    b.HasOne("BroadlinkWeb.Models.Entities.BrDevice", "BrDevice")
                        .WithMany()
                        .HasForeignKey("BrDeviceId");
                });
#pragma warning restore 612, 618
        }
    }
}
